[package]
name = "LiquidityLayer"
version = "1.2.0"
published-at = "0x3fdcd4efe728d281142f74760d62fc64986f8da88a7c6e4bb39d018efd70ca3f"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-1.0.0
rev = "09b2081498366df936abae26eea4b2d5cafb2788"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# testnet-1.0.0
rev = "de8360c7c25f52bf2593721a82cd6c7b66001faf"

[dependencies.Permissions]
local = "./../permissions"

[dependencies.Authlist]
local = "./../authlist"

[dependencies.Allowlist]
local = "./../allowlist"

[dependencies.Request]
local = "./../request"

[dependencies.Kiosk]
local = "./../kiosk"

[dependencies.Utils]
local = "./../utils"

[addresses]
liquidity_layer = "0x3fdcd4efe728d281142f74760d62fc64986f8da88a7c6e4bb39d018efd70ca3f"
