[package]
name = "Launchpad"
version = "1.2.0"
published-at = "0xba0811db92a433a3eff8afeabfeb81d7b8216e7ef4d3a0c580eaf2792410d3b4"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-1.0.0
rev = "09b2081498366df936abae26eea4b2d5cafb2788"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# testnet-1.0.0
rev = "de8360c7c25f52bf2593721a82cd6c7b66001faf"

[dependencies.Kiosk]
local = "./../kiosk"

[dependencies.Pseudorandom]
local = "./../pseudorandom"

[addresses]
ob_launchpad = "0xba0811db92a433a3eff8afeabfeb81d7b8216e7ef4d3a0c580eaf2792410d3b4"
