[package]
name = "NftProtocol"
version = "0.27.0"
published-at = "0x49da9700dd1db4f99e46fdaad2b867d32e0adb068e162c33eeeed3ab1416ad09"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# devnet-0.29.0
rev = "82c9c80c11488858f1d3930f47ec9f335a566683"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# devnet-0.29.0
rev = "f5242d0415b35fe48344e83cfd60924725fed23d"

[addresses]
nft_protocol = "0x49da9700dd1db4f99e46fdaad2b867d32e0adb068e162c33eeeed3ab1416ad09"
