[package]
name = "OBKiosk"
version = "0.0.0"
published-at = "0x"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-0.32.0
rev = "cab7e9762d4d75126a78fdd009b405745657fe57"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# devnet-0.32.0
rev = "c43b53f5d8b519e86d4a64ad0cf6787a7528b01b"

[dependencies.Witness]
local = "./../witness"

[dependencies.Request]
local = "./../request"

[dependencies.OBTest]
local = "./../ob_test"

[addresses]
ob_kiosk = "0x"
