[package]
name = "gutenberg"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
strfmt = "0.2"
gumdrop = "0.8.1"

[dev-dependencies]
pretty_assertions = "1.3.0"
