name: sui-test
run-name: Testing Sui packages

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, dev ]

  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Sui SDK
        run: |
          source .env

          wget -qO sui https://github.com/MystenLabs/sui/releases/download/${SUI_VERSION}/sui
          chmod +x sui

      - name: Run test for all modules
        run: |
          find . -name "Move.toml" |
          while read PACKAGE; do ./sui move test -p $PACKAGE; done

