[package]
name = "NftProtocol"
version = "1.0.0"
published-at = "0x2eead14abcb5a228b62a274ad22510555365f3f8e0af01bd6fb5de689f98f325"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# testnet-0.33.0
rev = "c525ba6489261ff6db65e87bf9a3fdda0a6c7be3"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# devnet-0.33.0
rev = "38743a3700abf8577a17e2751e82a4c0c249dfb3"

# TODO: This dependency should be removed in the long run
[dependencies.Witness]
local = "./../witness"

[dependencies.Authlist]
local = "./../authlist"

[dependencies.Allowlist]
local = "./../allowlist"

[dependencies.Request]
local = "./../request"

[dependencies.Kiosk]
local = "./../kiosk"

[dependencies.LiquidityLayer]
local = "./../liquidity_layer"

[dependencies.Utils]
local = "./../utils"

[addresses]
nft_protocol = "0x2eead14abcb5a228b62a274ad22510555365f3f8e0af01bd6fb5de689f98f325"
